In [ ]:
#numpy-numerical python 

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [29]:
a1=np.array([1,2,3,4,5,5],dtype='float')#ndarray-multidimensonal arrays
print(a1)
print(a1.shape)
print(a1.ndim)
print(a1[0])
print(len(a1))
#slicing
print(a1[::2])
print(a1[2::2])

[1. 2. 3. 4. 5. 5.]
(6,)
1
1.0
6
[1. 3. 5.]
[3. 5.]


In [86]:
help(int)

Help on class int in module builtins:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Built-in subclasses:
 |      bool
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      self != 

In [19]:
a1[1]='10'
print(a1)

[ 1 10  3  4  5  5]


In [84]:
a2=np.array([2,'ok',56.8,90])
print(a2)
print(type(a2))
print(a2.dtype)#unicotype

['2' 'ok' '56.8' '90']
<class 'numpy.ndarray'>
<U32


In [28]:
print(a1.dtype)

int32


In [36]:
sum=0
for i in a1:
    sum+=i
print(sum)

20.0


In [37]:
for i in a1:
    if(i%2==0):
        print(i)

2.0
4.0


In [45]:
print(np.min(a1)+1)

2.0


In [82]:
a3=[7,8,9,4,6]
for i in a3:
     a3.sort(reverse=True)
print(a3)
print(a3[1])

[9, 8, 7, 6, 4]
8


In [7]:
a1=[]
n=int(input('enter the num:'))
for i in range(1,10+1):
       s=n*i  
       a1.append(s)
print('a1',a1)
a2=np.array(a1[2:6])
print(a2)

enter the num:2
a1 [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
<class 'numpy.ndarray'>
[ 6  8 10 12]


In [9]:
a1=np.arange(0,11,2)

In [10]:
a1

array([ 0,  2,  4,  6,  8, 10])

In [11]:
a1=np.arange(1.5,5,0.5)
a1

array([1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [174]:
#list of 1d arrays
a2d=np.array([[1,2,3],[4,5,6]])

In [13]:
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a2d.shape

(2, 3)

In [15]:
a2d.ndim

2

In [16]:
a2d_zero=np.zeros((2,3))

In [19]:
a2d_zero

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
a2d_zero=np.ones((2,3))


In [20]:
a1=np.arange(1,10)

In [21]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a2=a1.reshape(3,3)

In [24]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
#random
np.random.random()#range is 0 to 1

0.3714551921414291

In [31]:
np.random.randint(11,20)

15

In [251]:
np.random.uniform(11,20)

11.846891673171632

In [250]:
a1=np.random.randint(11,20,2)

In [36]:
a1

array([15, 18])

In [39]:
a_2d=np.random.randint(1,10,(4,4))

In [40]:
a_2d

array([[1, 3, 4, 8],
       [8, 8, 3, 4],
       [3, 6, 6, 9],
       [5, 3, 5, 7]])

In [41]:
a_2d=np.random.uniform(1,10,(3,5))

In [43]:
a_2d

array([[5.66395175, 7.46638841, 4.55376816, 3.27360782, 9.6346154 ],
       [5.70327255, 3.87473292, 8.67861974, 8.51023042, 4.63413769],
       [2.52419158, 7.28282059, 4.39980521, 2.79076227, 4.51352522]])

In [44]:
np.sum(a1)

33

In [45]:
np.mean(a1)

16.5

In [48]:
np.min(a2)

1

In [47]:
np.max(a2)

9

In [50]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
np.sort(a2)[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [54]:
a2>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [55]:
a2+5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [56]:
a1*4

array([60, 72])

In [57]:
a1/3


array([5., 6.])

In [58]:
a1>5

array([ True,  True])

In [59]:
a1[a1>5]

array([15, 18])

In [77]:
#2d
a_2d=np.random.randint(1,11,(3,2))

In [78]:
a_2d

array([[ 6,  3],
       [ 5,  4],
       [ 8, 10]])

In [64]:
a_2d.sum()

52

In [65]:
np.sum(a_2d,axis=0)

array([27, 25])

In [66]:
np.sum(a_2d,axis=1)

array([ 9,  7,  9,  8, 19])

In [68]:
np.mean(a_2d,axis=0)

array([5.4, 5. ])

In [69]:
np.min(a_2d,axis=1)

array([2, 1, 3, 3, 9])

In [70]:
a1=a_2d.flatten()

In [71]:
a1

array([ 2,  7,  6,  1,  6,  3,  3,  5, 10,  9])

In [72]:
a1=a_2d.ravel()

In [73]:
a1

array([ 2,  7,  6,  1,  6,  3,  3,  5, 10,  9])

In [74]:
a_2d[1,1]

1

In [81]:
a_2d

array([[ 6,  3],
       [ 5,  4],
       [ 8, 10]])

In [80]:
a_2d[2,1]

10

In [83]:
a_2d[1:3,1:]

array([[ 4],
       [10]])

In [91]:
a1=np.zeros(4,dtype='int')


In [92]:
a1

array([0, 0, 0, 0])

In [93]:
a1.shape

(4,)

In [98]:
a1=np.ones(4,dtype='int')

In [90]:
a1.ndim

1

In [99]:
a1[3]=4

In [100]:
a1

array([1, 1, 1, 4])

In [101]:
a1[[3,2,1]]=[100,200,10]#assigning value

In [102]:
a1

array([  1,  10, 200, 100])

In [109]:
a1=np.arange(5,51,5)

In [110]:
a1

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [124]:
a2=np.zeros(10,dtype='int')

In [125]:
print(a2)

[0 0 0 0 0 0 0 0 0 0]


In [127]:
a2=np.arange(11,32,2)

In [129]:
print(len(a2))

11


In [149]:
a2=np.zeros(len(np.arange(11,32,2)),dtype='int')   

In [155]:
id(a2)

2591206285936

In [157]:
no=11
for i in range(0,len(a2)):
    a2[i]=no
    no+=2
print(id(a2))
print(type(a2))

2591206285936
<class 'numpy.ndarray'>


In [162]:
a3=np.arange(100,1,-10)

In [163]:
a3

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [164]:
a3.sum()

550

In [165]:
np.sum(a3)

550

In [166]:
a3.mean()

55.0

In [167]:
np.mean(a3)

55.0

In [168]:
a3.max()

100

In [169]:
np.max(a3)

100

In [170]:
np.average(a3)

55.0

In [171]:
np.min(a3)

10

In [172]:
a3.min()

10

In [176]:
#2d array
a2=np.array([[1,2],[2,3],[8,9]])

In [177]:
print(a2[1])

[2 3]


In [178]:
print(a2[1,1])

3


In [179]:
print(a2.shape)

(3, 2)


In [185]:
a_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
sum=0
for i in a_2d:
    for j in i:
        sum+=j
print(sum)

45


In [190]:
a_1d=np.array([1,2,3,4])
a1=np.array([6,7,8])
a_1d+a1

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [191]:
a_1d=np.array([1,2,3,4])
a1=np.array([6,7,8,9])
a_1d+a1#we need to have same shape

array([ 7,  9, 11, 13])

In [196]:
a_1d=np.array([[1,2,3,4],[1,2,3,4]])
a1=np.array([6,3,4,5])
a_1d+a1

array([[7, 5, 7, 9],
       [7, 5, 7, 9]])

In [197]:
a1*2

array([12,  6,  8, 10])

In [201]:
arr=np.arange(5,15)
arr1=np.array([2])
arr3=arr*arr1
print(arr3)

[10 12 14 16 18 20 22 24 26 28]


In [217]:
arr=np.arange(5,15).reshape(2,5)
print(arr)
arr1=np.arange(1,11).reshape(2,5)
print(arr1)
a5=arr+arr1

[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [218]:
a5

array([[ 6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24]])

In [219]:
a5.sum()

150

In [220]:
np.sum(a5)

150

In [221]:
a5.min()

6

In [222]:
a5.max()

24

In [223]:
a5.mean()

15.0

In [229]:
np.sum(a5,axis=0,keepdims=True)

array([[22, 26, 30, 34, 38]])

In [230]:
a5

array([[ 6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24]])

In [232]:
np.min(a5,axis=1)

array([ 6, 16])

In [242]:
np.average(a5,axis=0)


array([11., 13., 15., 17., 19.])

In [243]:
#random
#np.random()
#np.randint()
#unifor()

<module 'numpy.random' from 'D:\\New folder\\Python\\envs\\envr1\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [247]:
a1=np.random.random()

In [248]:
a1

0.6208595540783061

In [253]:
o=np.random.randint(20,30,15)

In [254]:
type(o)

numpy.ndarray

In [255]:
o=np.random.uniform(20,30,15)

In [256]:
o

array([29.19543017, 25.24455529, 21.35730396, 28.68317571, 29.43887452,
       29.26850438, 24.24482974, 23.47990923, 26.69994951, 22.43514737,
       23.60610733, 26.01379966, 29.18636251, 27.48264814, 23.11956331])

In [257]:
o=np.random.uniform(15)

In [258]:
o

13.624715778962535

In [270]:
i=np.random.randint(10,20,(3,3))

In [272]:
i

array([[10, 17, 11],
       [15, 11, 15],
       [19, 12, 19]])

In [265]:
i=np.random.random((3,3))

In [266]:
i

array([[0.38768984, 0.75090277, 0.21570681],
       [0.14943673, 0.70054651, 0.74730989],
       [0.80448077, 0.52660772, 0.26417591]])

In [268]:
i=np.random.uniform(10,20,(3,3))

In [269]:
i

array([[16.74364448, 17.97353806, 11.5582855 ],
       [14.86285306, 11.50489091, 10.34033136],
       [10.07385952, 17.94338084, 15.38609399]])

In [273]:
#slicing[row:col]
i[0::]

array([[10, 17, 11],
       [15, 11, 15],
       [19, 12, 19]])

In [285]:
i[0:,1:]

array([[17, 11],
       [11, 15],
       [12, 19]])

In [4]:
#show me sum of all inner elements
ap=np.random.randint(5,16,(4,4))
ap

array([[14, 15, 14, 12],
       [10, 15,  9, 13],
       [ 8, 15,  8, 12],
       [12, 14,  9,  9]])

In [5]:
ap[1:2:,0::3]#sum of boundary elements

array([[10, 13]])

In [23]:
ap[2::,0::3]

array([[ 8, 12],
       [12,  9]])

In [20]:
a1=np.random.randint(5,25,15).reshape(5,3)
print(a1)
a2=np.random.randint(200,215,15).reshape(5,3)
print(a2)

[[11 22 12]
 [ 5 12 20]
 [19 23 16]
 [17  5 13]
 [16 17 14]]
[[213 200 214]
 [208 205 209]
 [201 212 200]
 [208 210 201]
 [212 208 204]]


In [345]:
np.concatenate([a1,a2],axis=1)

array([[  8,   8,  21, 208, 203, 213],
       [  5,  21,   7, 201, 208, 205],
       [ 23,  23,   7, 201, 208, 200],
       [ 15,  22,  13, 209, 212, 206],
       [ 18,  12,  13, 209, 206, 207]])

In [347]:
#horizontal stack-column wise
np.hstack((a1,a2))

array([[  8,   8,  21, 208, 203, 213],
       [  5,  21,   7, 201, 208, 205],
       [ 23,  23,   7, 201, 208, 200],
       [ 15,  22,  13, 209, 212, 206],
       [ 18,  12,  13, 209, 206, 207]])

In [348]:
#rowvise-verticle
np.vstack((a1,a2))

array([[  8,   8,  21],
       [  5,  21,   7],
       [ 23,  23,   7],
       [ 15,  22,  13],
       [ 18,  12,  13],
       [208, 203, 213],
       [201, 208, 205],
       [201, 208, 200],
       [209, 212, 206],
       [209, 206, 207]])

In [350]:
np.transpose(a1)


array([[ 8,  5, 23, 15, 18],
       [ 8, 21, 23, 22, 12],
       [21,  7,  7, 13, 13]])

In [351]:
a1>3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [353]:
a1>15

array([[False, False,  True],
       [False,  True, False],
       [ True,  True, False],
       [False,  True, False],
       [ True, False, False]])

In [357]:
a1[a1[0]>3]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 3

In [359]:
a1[a1>15]

array([21, 21, 23, 23, 22, 18])

In [364]:
np.sum(a1[a1%2==0])

68

In [367]:
#where
np.where(a1>15,a1,0)

array([[ 0,  0, 21],
       [ 0, 21,  0],
       [23, 23,  0],
       [ 0, 22,  0],
       [18,  0,  0]])

In [374]:
np.where(a1%2==0,a1,a1**2)

array([[  8,   8, 441],
       [ 25, 441,  49],
       [529, 529,  49],
       [225,  22, 169],
       [ 18,  12, 169]])

In [387]:
#nan-not a null
a7=np.array([45,7,np.nan,23,24,np.nan])
print(a7)
a8=np.where(np.isnan(a7),a7,a7**2)
print(a8)

[45.  7. nan 23. 24. nan]
[2025.   49.   nan  529.  576.   nan]


In [376]:
a7

array([ 1., 23., 67., nan, 89., nan])

In [385]:
np.where(np.isnan(a7),a7,a7**2)

array([1.000e+00, 5.290e+02, 4.489e+03,       nan, 7.921e+03,       nan])

In [388]:
a1=np.array([1,2,3,4])
a2=np.array([1,2,3,4])

In [389]:
a1.dot(a2)

30

In [393]:
a1=np.random.randint(1,10,9).reshape(3,3)
print(a1)
a2=np.random.randint(5,10,15).reshape(3,5)
print(a2)

[[8 8 3]
 [3 9 8]
 [9 9 2]]
[[8 7 9 7 7]
 [5 6 5 6 5]
 [5 6 6 9 8]]


In [394]:
a1.dot(a2)

array([[119, 122, 130, 131, 120],
       [109, 123, 120, 147, 130],
       [127, 129, 138, 135, 124]])