# Assignment-2

In [2]:
import numpy as np

In [7]:
#1.Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).
a_1d=np.array([[1,2,3],[1,2,3]])
a1=np.array([6,3,4])
a_1d+a1

array([[7, 5, 7],
       [7, 5, 7]])

In [66]:
#2. How to replace all missing values with 0 in a numpy array?
a7=np.array([45,7,np.nan,23,24,np.nan])
print(a7)
a8=np.where(np.isnan(a7),0,a7)
print(a8)

[45.  7. nan 23. 24. nan]
[45.  7.  0. 23. 24.  0.]


In [77]:
#3.How to get the second largest value of an array when grouped by another array?
x = np.arange(1,10+1)
print("Original array:",x)
print (x[np.argsort(x)[-n:]])

Original array: [ 1  2  3  4  5  6  7  8  9 10]
[10]


In [64]:
#4.Write a NumPy program to create a 3x3x3 array with random values. 
a7=np.random.random((3,3,3))
print(a7)

[[[0.84627083 0.62373457 0.39278055]
  [0.33357436 0.84921669 0.0774361 ]
  [0.12261983 0.88359714 0.43950695]]

 [[0.90681691 0.79222338 0.87440233]
  [0.60293841 0.58284391 0.2511912 ]
  [0.00837633 0.90616058 0.99339144]]

 [[0.60719435 0.90283338 0.10877561]
  [0.09857837 0.67699279 0.76240267]
  [0.62777487 0.85818018 0.4821726 ]]]


In [57]:
#5. Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.
a=np.random.randint(1,10,15)
print(a)
print('**************')
a[a.argmax()] = -1
print(a)


[9 2 6 7 9 8 2 2 4 9 5 9 5 8 5]
**************
[-1  2  6  7  9  8  2  2  4  9  5  9  5  8  5]


In [67]:
#6.Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ",x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array:  [[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [4]:
#7.Write a NumPy program to get the unique elements of an array. 
a=np.array([1,1,2,3,4,8,8])
b=np.unique(a)
print(b)

[1 2 3 4 8]


In [32]:
#8.Write a NumPy program to get the powers of an array values element-wise.
a=np.arange(1,10)
print('a:',a)
print('powers of a:',a**2)

a: [1 2 3 4 5 6 7 8 9]
powers of a: [ 1  4  9 16 25 36 49 64 81]


In [31]:
#9.Write a NumPy program to remove the negative values in a NumPy array with 0.
c=np.array([1,2,-4,5,6,-9,-8,6,55])
print(np.where(c>0,c,0))

[ 1  2  0  5  6  0  0  6 55]


In [26]:
#10.Write a NumPy program to calculate the absolute value element-wise. 
b=np.array([1,1.2,2,2.2,3,1j])
np.abs(b)

array([1. , 1.2, 2. , 2.2, 3. , 1. ])

In [78]:
#11.Write a NumPy program to replace odd number in 2d array by its square . 
a1=np.random.randint(1,10,(3,3))
print(np.where(a1%2!=0,a1,a1**2))

[[ 3 16  9]
 [ 3  7 64]
 [ 7  5  9]]
